version: "3.7"
services:

  web:
    container_name: "web"
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - custom

  app:
    container_name: "app"
    image: app
    # environment:
    #   - smth=hewwo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ":8000"
    networks:
      - custom

networks:
  custom:
    driver: bridge
